import requests
import json
import urllib.parse

url = "https://api.github.com/repos/owid/owid-datasets/contents/datasets"
resp = requests.get(url, timeout=10)
if resp.status_code == 200:
    datasets = [item["name"] for item in resp.json() if item["type"] == "dir"]
    matches = [d for d in datasets if any(w in d.lower() for w in ["instability", "political", "conflict", "democracy", "regime"])]
    print("Matching datasets:", matches)
    
    # If there is a matching one, let's find the exact CSV url
    # We saw the title was "The Rise and Fall of Nations: Tracking Global Political Instability"
    # Wait, the title was generated by Gemini! The dataset name could be something else, like "Episodes of Regime Transformation" or "Political Instability" or something.
    # Let's search the datasets for any matching name and print their CSV names and contents.
    for name in matches[:5]:
        print(f"\n--- Dataset: {name} ---")
        item_url = f"https://api.github.com/repos/owid/owid-datasets/contents/datasets/{urllib.parse.quote(name)}"
        item_resp = requests.get(item_url, timeout=10)
        if item_resp.status_code == 200:
            files = [f["name"] for f in item_resp.json() if f["type"] == "file"]
            csv_files = [f for f in files if f.endswith(".csv")]
            print("CSV files:", csv_files)
            if csv_files:
                raw_url = f"https://raw.githubusercontent.com/owid/owid-datasets/master/datasets/{urllib.parse.quote(name)}/{urllib.parse.quote(csv_files[0])}"
                print("Raw URL:", raw_url)
                # print first few rows
                try:
                    import pandas as pd
                    df = pd.read_csv(raw_url)
                    print("Shape:", df.shape)
                    print("Columns:", list(df.columns))
                    print(df.head(2))
                except Exception as e:
                    print("Error loading:", e)
else:
    print("Failed to fetch repository contents:", resp.status_code)
